### ISSUE TITLE
Deployment to dev and prod failed health check with this traceback

### ISSUE THREAD

**Issue by bmbouter** [pulp/analytics.pulpproject.org#35]
```
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/app/pulpanalytics/views.py", line 230, in get
    self._label_xy_versions_data_for_plugin(context, "age_count", fill=True)
  File "/srv/app/pulpanalytics/views.py", line 150, in _label_xy_versions_data_for_plugin
    new_data[0]["fill"] = True
IndexError: list index out of range
```

**Comment by bmbouter** [comment]
This is resolved in dev and production now.
